# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    default_locale: fr # '%env(APP_LOCALE)%'
    secret: '%env(APP_SECRET)%'
    session:
        enabled: true
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: en
        paths:
            - '%kernel.project_dir%/translations'

parameters:
    locale: fr # '%env(APP_LOCALE)%'
    app_secret: '%env(APP_SECRET)%'

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
