framework:
    default_locale: fr # '%env(APP_LOCALE)%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        logging: true
        fallbacks:
            - en
        # providers:
        #     crowdin:
        #         dsn: '%env(CROWDIN_DSN)%'
        #     loco:
        #         dsn: '%env(LOCO_DSN)%'
        #         domains: ['messages']
        #         locales: ['fr', 'en']
        #     lokalise:
        #         dsn: '%env(LOKALISE_DSN)%'
        #     phrase:
        #         dsn: '%env(PHRASE_DSN)%'

        # paths:
        #     - '%kernel.project_dir%/translations'








